### ISSUE TITLE
AssertionError [ERR_ASSERTION]: rimraf: missing path

### ISSUE THREAD

**Issue by yeskiy** [ortexx/express-form-data#5]
` at Object.rimraf (C:\Users\****\Projects\Opened\rest_api_server\node_modules\fs-extra\lib\remove\rimraf.js:35:3)
    at C:\Users\****\Projects\Opened\rest_api_server\node_modules\universalify\index.js:13:12
    at new Promise (<anonymous>)
    at Object.rimraf (C:\Users\****\Projects\Opened\rest_api_server\node_modules\universalify\index.js:7:14)
    at C:\Users\****\Projects\Opened\rest_api_server\node_modules\express-form-data\index.js:51:17
    at new Promise (<anonymous>)
    at ServerResponse.<anonymous> (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express-form-data\index.js:50:22)
    at ServerResponse.emit (events.js:323:22)
    at ServerResponse.EventEmitter.emit (domain.js:482:12)
    at onFinish (_http_outgoing.js:730:10)
    at onCorkedFinish (_stream_writable.js:721:5)
    at afterWrite (_stream_writable.js:528:5)
    at afterWriteTick (_stream_writable.js:515:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:3508) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at ServerResponse.header (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express\lib\response.js:267:15)
    at _callee2$ (C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\/editRoutes.js:147:17)
    at tryCatch (C:\Users\****\Projects\Opened\rest_api_server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\****\Projects\Opened\rest_api_server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (C:\Users\****\Projects\Opened\rest_api_server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\editRoutes.js:26:103)
    at _next (C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\editRoutes.js:28:194)
    at C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\editRoutes.js:28:364
    at new Promise (<anonymous>)
    at C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\editRoutes.js:28:97
    at C:\Users\****\Projects\Opened\rest_api_server\src\api\routes\/editRoutes.js:132:5
    at Layer.handle [as handle_request] (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\****\Projects\Opened\rest_api_server\node_modules\express\lib\router\route.js:137:13)
(node:3508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch 
block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Sample code:** 
```javascript
import routes from '../api';
import bodyParser from 'body-parser';
import formData from 'express-form-data'
import os from 'os';
import { generalErr } from '../api/middlewares';
export default ({ app, fireAdmin, fireClient, mailAdmin, liqpayAdmin, bbService }) => {
    // Middleware that transforms the raw string of req.body into json
    app.use(bodyParser.json());
    //url encoded to body
    app.use(bodyParser.urlencoded({ extended: true }));
    app.use(formData.parse({
        uploadDir: os.tmpdir(),
        autoClean: true
    }));
    // delete from the request all empty files (size == 0)
    // app.use(formData.format());
    // change the file objects to fs.ReadStream 
    // app.use(formData.stream());
    // union the body and the files
    // app.use(formData.union());
    app.use('/', routes(fireAdmin, fireClient, mailAdmin, liqpayAdmin, bbService));
    app.use(generalErr);
}
```

**This error appears when I try to upload more than 1 file**

**Comment by ortexx** [comment]
Hey! Check the new version.
